name: Go

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      
    - name: Installing lint
      run: make lint-install
      
    - name: Lint
      run: make lint

    - name: Build
      run: go run main.go

    - name: Test
      run: go test -v
